BLog/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("",views.homepage,name="blog_page"),
    path("save/",views.save,name="save"),
    path("create/new/",views.create,name="create"),
    path("<id>/edit/",views.edit,name="edit"),
    path("preview/fetch/",views.preview_data,name="preview_data"),
    path("submit/post/",views.post,name="post"),
    path("read/<user>/<title>/<id>/",views.mainpage,name="mainpage"),
    path("comment/post/",views.comment,name="comment"),
    path("upload/body/",views.image_upload, name="image_upload"),
    path("analytics/data/fetch/",views.analytics_data,name="analytics_data"),
    path("analytics/data/fetch/all/",views.analytics_dataall,name="analytics_dataall"),
]

Majorproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("Core.urls")),
    path('ckeditor/',include("ckeditor_uploader.urls")),
    path("chat/",include("Chat.urls")),
    path("discuss/",include("Discuss.urls")),
    path("blogs/",include("BLog.urls")),
    path("playground/",include("Playground.urls")),
    path("notebook/",include("Notebook.urls")),
    path("explore/",include("explore.urls")),
    path("coding/",include("coding.urls")),
    path("accounts/",include("accounts.urls")),
     path('socialaccounts/', include('allauth.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name="logout"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BLog/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField 
from ckeditor_uploader.fields import RichTextUploadingField
import re 
from datetime import date
from django.utils import timezone 
# Create your models here. 

   
class Articles(models.Model):
    STATUS_CHOICES = (
		("Drafts", "Drafts"),("Published", "Published"),)
    BROADCAST_CHOICES = (
		('Public', 'Public'),('Private', 'Private'),)
    user = models.ForeignKey(User, related_name='project_username_2', to_field='username', on_delete=models.CASCADE)
    title = models.TextField(max_length = 10000,default=" ",blank=True,unique=False, null=True)
    date = models.DateTimeField(auto_now_add = True)
    edited = models.DateTimeField(auto_now = True)
    image = models.ImageField(upload_to='users/images',blank=True,null=True,default="/users/images/undraw_developer_activity_bv83_1HLxfQZ.svg/")
    content = RichTextUploadingField(null=True)
    description = models.TextField(blank=True,default="")
    tags = models.CharField(max_length=300,blank=True,default="",null=True,help_text='Add comma( ,) seperated tags!!')
    status = models.CharField(max_length=30,choices=STATUS_CHOICES,default='Drafts')
    broadcast = models.CharField(max_length=10,choices=BROADCAST_CHOICES,default='Public')
    like = models.ManyToManyField(User,default=None,blank=True,related_name="likes_title")
    dislike = models.ManyToManyField(User,default=None,blank=True,related_name="dislikes_title")
    bookmark = models.ManyToManyField(User,default=None,blank=True,related_name="bookmark_title")
    class Meta:
        ordering = ['-id']
    def __str__(self):
        return str(self.title)
    @property
    def num_likes(self):
        return self.like.all().count()

    @property
    def num_dislikes(self):
        return self.dislike.all().count()
    def __init__(self, *args, **kwargs):
        super(Articles, self).__init__(*args, **kwargs)
        self._date = self.date
    
    def save(self, *args, **kwargs):
        if not self._date and self.date:
            self.edited = django.timezone.now()
        super(Articles, self).save(*args, **kwargs)
    @property
    def countview(self):
        c = 0
        for i in ArticleViewCount.objects.filter(article_instance = self):
            c += i.count

        return c

class ArticleViewCount(models.Model):
    article_instance = models.ForeignKey(Articles, related_name='view_count', on_delete=models.CASCADE)
    user = models.ManyToManyField(User, related_name="articleviewuser")
    count = models.IntegerField(blank=True, null=True, default=0)
    created = models.DateField(blank=True, default=date.today)
    def __str__(self):
        return self.article_instance.title
    

class BlogComment(models.Model):
    user = models.ForeignKey(User, related_name='blog_comment_user', to_field='username', on_delete=models.CASCADE,default="")
    question = models.ForeignKey(Articles, related_name='blog_comment_ques',on_delete=models.CASCADE,default="")
   
    parent = models.ForeignKey('self',null=True,blank=True,on_delete=models.CASCADE,related_name="replies_name")
    body = models.TextField(blank=False)
    created = models.DateTimeField(auto_now_add=True,null=True)
    active = models.BooleanField(default=True)
    like = models.ManyToManyField(User,related_name="blog_comment_like")
    dislike = models.ManyToManyField(User,related_name="blog_comment_dislike")
    class Meta:
        ordering = ('-created',)
    def children(self):
        return BlogComment.objects.filter(parent=self).order_by("id")

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True
    @property
    def sorting(self):
        return BlogComment.objects.filter(parent = self).order_by("created")
    def __str__(self):
        return self.body

BLog/forms.py
from django import forms

from .models import *

class Article_form(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea(attrs={'required':True,'autofocus':True,'placeholder':"Write title of your story.",'style':'font-size:24px; height:60px; font-weight:600; padding-top:10px; border:1px solid rgb(0,0,0,0.1);'}))
    
    class Meta:
        model = Articles
        fields = ('title','image','content')

BLog/views.py
from django.shortcuts import render
from .forms import *
from .models import *
from django.forms.models import model_to_dict
import json
import re
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from datetime import date
import datetime
# Create your views here.
def homepage(request):
    
    context = {}
    data = Articles.objects.filter(status = 'Published').order_by("-edited")
    context['carousel'] = data[:1]
    context['side'] = data[1:5]
    context['data'] = data[5:]

    return render(request,'Blog/homepage.html',context)
@login_required
def create(request):
    context = {}
    context['form'] = Article_form()
    context['id'] = 0    
    return render(request,'Blog/create.html',context)

def edit(request,id):
    context = {}
    context['edit'] = True
    instance = Articles.objects.get(id = id)
    if request.user == instance.user:
        context['title'] = instance.title
        context['content'] = instance.content
        context['image'] = instance.image
        context['id'] = id
        context['link'] = instance.image
        context['tags'] = instance.tags
        context['broadcast'] = instance.broadcast
        return render(request,'Blog/edit.html',context)
    else:
        return HttpResponseRedirect('/page_not_found/')

def save(request):
    if request.method == 'POST':
        image = request.FILES.get('image')
        title = request.POST.get('title')
        content = request.POST.get('value') 
        instance = request.POST.get('id')
        method = request.POST.get('method')

        if image is not None or title != "" or content != '<p class="ck-placeholder" data-placeholder="Write your story here. Add images or a video for visual impact."><br data-cke-filler="true"></p>' :
            if title == "" or title is None :
                title = "Untitled Draft"
            
            if instance == '0' and method == 'create':
                ins = Articles(user = request.user,image = image,title = title,content = content)
                ins.save()
            else:
                ins = Articles.objects.get(id = instance)
                if image is not None:
                    ins.image = image
                ins.status = 'Drafts'
                ins.title = title
                ins.content = content
                ins.save()
            return HttpResponse(json.dumps({'status':1,"id":ins.id}))
        else:
            return HttpResponse(json.dumps({'status':0}))

def cleanhtml(raw_html):
  cleanr = re.compile('<.*?>')
  cleantext = re.sub(cleanr, '', raw_html)
  return cleantext
def preview_data(request):
    context = {}
    instance = request.GET.get('id')
    instance = Articles.objects.get(id = instance)
    context['image'] = "/media/"+str(instance.image)
    context['title'] = instance.title
    context['desc'] = cleanhtml(instance.content)[:147] + "..."
    context['broadcast'] = instance.broadcast
    context['tags'] = instance.tags
    return HttpResponse(json.dumps(context))

def post(request):
    if request.method == 'POST':
        method = request.POST.get('method')
        tags = request.POST.get('tags')
        public = request.POST.get('public')
        instance = request.POST.get('id')
       
        ins = Articles.objects.get(id = instance)
        ins.tags = tags
        ins.status = method

        if public == "1":
            ins.broadcast = "Public"
        else:
            ins.broadcast = "Private"
        

        ins.save()
        
        if method == 'Published':
            ty = "Published"
        else:
            ty = "Drafts"
        return HttpResponse(json.dumps(f"/profile/{request.user}/?method=Articles&type={ty}"))

def mainpage(request,user,title,id):
    context = {}
    ins = Articles.objects.get(id = id)

    context['data'] = ins
    context['side'] = Articles.objects.filter(user = ins.user, status = "Published").count()
    if ArticleViewCount.objects.filter(article_instance = ins, created = datetime.datetime.strptime(str(date.today()),"%Y-%m-%d")).exists():
        instance = ArticleViewCount.objects.get(article_instance = ins, created = datetime.datetime.strptime(str(date.today()),"%Y-%m-%d"))
        if request.user not in instance.user.all():
            if request.user in User.objects.all():
                instance.count +=1
                instance.user.add(request.user)
                instance.save()
            else:
                instance.count +=1
                instance.save()

            
    else:
        instance = ArticleViewCount(article_instance = ins, count = 1)
        instance.save()

    return render(request,'Blog/mainpage.html',context)

def comment(request):
    if request.method == 'POST':
        data = request.POST.get('value')
        print(data)
    return HttpResponse(json.dumps(""))
@csrf_exempt 
def image_upload(request):
    if request.method == 'POST':
        pass
    return ""


def analytics_data(request):
    aid = request.GET.get('id')
    curr = request.GET.get('index')
    update = request.GET.get('update')
    date_field = []
    view_field = []
    if(int(aid) == -1):
        ins = Articles.objects.filter(user = request.user, status = 'Published').order_by("-id").first()
        
    else:
        ins = Articles.objects.get(user = request.user,id = aid,status='Published')
    instance = ArticleViewCount.objects.filter(article_instance = ins).order_by('-created')[:7]
    for i in instance:
        date_field.append(str(i.created.strftime("%b %d, %Y")))
        view_field.append(i.count)
    while len(date_field) !=7:
        date_field.append("")
        view_field.append(0)
    stack = [ins.like.all().count(),sum([j.count for j in ins.view_count.all()]),ins.bookmark_article.all().count(),ins.blog_comment_ques.all().count()]
    context = {"x":date_field[::-1],"y":view_field[::-1],"title":ins.title,"stack":stack}
    return HttpResponse(json.dumps(context))

def analytics_dataall(request):
    user = request.GET.get("user")
    if user is None:
        user = request.user
    else:
        user = User.objects.get(username = user)
    curr = request.GET.get('index')
    update = request.GET.get('update')
    like_field = 0
    view_field = 0
    title_field = 0
    comment_field=0
    saves_field=0
    ins = Articles.objects.filter(user = user, status = 'Published')
    for i in ins:
    
        like_field += i.like.all().count()
        comment_field += i.blog_comment_ques.all().count()
        saves_field += i.bookmark_article.all().count()
        view_field += sum([j.count for j in i.view_count.all()])
    published_count = ins.all().count()
    draft_count = Articles.objects.filter(user = request.user, status = 'Drafts').all().count()
    context = [like_field,view_field,saves_field,comment_field,published_count,draft_count]
    return HttpResponse(json.dumps(context))

BLog/templates/Blog/create.html
{% extends 'Core/snippets/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block header %}
{% include 'Core/snippets/header.html' %}
{% endblock %}
{% block jscss %}
<link href="https://myCDN.com/prism@v1.x/themes/prism.css" rel="stylesheet" />
<script src="https://myCDN.com/prism@v1.x/components/prism-core.min.js"></script>
	<script src="https://myCDN.com/prism@v1.x/plugins/autoloader/prism-autoloader.min.js"></script>
<script src="https://cdn.ckeditor.com/ckeditor5/27.1.0/decoupled-document/ckeditor.js"></script>
<script src="https://ckeditor.com/apps/ckfinder/3.5.0/ckfinder.js"></script>

{% endblock %}
{% block style %}
#div_id_image label{
    display:none;
}
#div_id_image{
    width:100%;
    height:100%;
  
  cursor:pointer;
  opacity:0;
  cursor:pointer;
  background-color:#fff;

}
#div_id_image input{
    width:100%;
    height:150px;
    opacity:0;
    cursor:pointer;
    background-color:#fff;
}
#div_id_title label{
    display:none;
}

#id_title{
    width:100%;
   
    border:none;
  
    
    resize:none;
  
   
   
}
#id_title:focus{
    border-color: #C9A56E;
    box-shadow: none;
    outline: 0 none;
}
#div_id_tags label{
    display:none;
}

#div_id_tags input{
    width:100%;
    margin-top:-13px;
    border:none;
    height:40px;
    font-size:20px;
   
   
}
#div_id_description label{
    display:none;
}

#div_id_description input{
    width:100%;
    margin-top:-13px;
    border:none;
    height:90px;
    font-size:20px;
   
   
}
textarea:focus,
input[type="text"]:focus,
input[type="password"]:focus,
input[type="datetime"]:focus,
input[type="datetime-local"]:focus,
input[type="date"]:focus,
input[type="month"]:focus,
input[type="time"]:focus,
input[type="week"]:focus,
input[type="number"]:focus,
input[type="email"]:focus,
input[type="url"]:focus,
input[type="search"]:focus,
input[type="tel"]:focus,
input[type="color"]:focus,
.uneditable-input:focus {   
  border-color: #C9A56E;
  box-shadow: none;
  outline: 0 none;
}
#div_id_content label{
    display:none;
}
#id_image{
{% if edit %}
    margin-top:-200px;
{% endif %}"
}
#editor{
    border:none;
    outline:none;
    box-shadow:none;
}
.cke_chrome , .cke_focus, .ck_toolbar{
   border:0px;
}
{% endblock %}

{% block body %}
<section class="pt-5">
    <div class="shadow-sm  d-flex justify-content-between align-items-center" style="margin-top: 13px; background-color: #FAFAFA; position: sticky; top:3.75rem; z-index:1000;">
        <div id="toolbar-container"></div>
        <div style="width:100%; " class="border p-1 d-flex justify-content-end align-items-center">
        
                <a class="nav-link" style="font-size: 12px;" href="#" id="running"></a>
            
           
               <a class="mr-3 p-0" style="font-size:12px;" href="#"> Draft in {{request.user.profile.first_name}} {{request.user.profile.last_name}}</a>
          
            <a class="btn btn-sm shadow mr-2" style="border:1px solid #2EA8E6; color: white; border-radius:20px; background-color: rgb(46, 168, 230,1);"><i class="fa fa-paper-plane"></i> Publish</a>
        </div>
    </div>
<div class="container">
    <div class="row">
        <div class="col-12 col-md-12 col-lg-10 offset-lg-1 mb-4">
            <form id="myform" method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                <div class="mt-3">
                    <div style="background-color: rgb(243, 242, 239); height:180px;" id="upload" >
                        <img src="{% static 'svg/upload.svg' %}" style="width:200px; margin-top:30px; position: absolute;  margin-left: auto; margin-right: auto; left: 0;
                        right: 0; text-align: center;"  alt="Cover Picture">
                        <input id="div_id_image" name="image" type="file" >
                    </div>
                     <input type="hidden" name="instance" value="{{id}}" id="hidden_instance">
                    <div id="preview" style="display: none;" class="">
                        <div class="d-flex justify-content-end">
                            <a class="btn btn-sm" onclick="show()" style="position:absolute; right:2rem; top:2rem; color: white; border:1px solid white; border-radius: 50%; "><i class="fa fa-trash"></i></a>
                        </div>
                        <div  class="" style="width: 100%;">
                            <img id="blah" src="/media/{{link}}/" alt="your image" style="display: none;  width:100%;" class="rounded" >
                        </div>
            
                    </div>
                   
                </div>
                <div class="mt-3">
                    <textarea name="title" style="width:100%; height:60px;  border:none; resize: none; font-size: 28px; font-weight: 600;" placeholder="Title of your story" class="pt-2"></textarea>
                </div>
                <div class="">
                  
                    <div id="editor"></div>
                
                </div>
                <div>

                </div>
            </form>
        </div>
    </div>
</div>
</section>
{% endblock %}

{% block body1 %}
<nav class="navbar navbar-expand-lg  fixed-top shadow-sm d-flex  align-items-center border-bottom" style="height:60px;background:white;">
    <div class="container">
        <a class="navbar-brand" href="/">
            <div style="color:#393E41; font-size: 20px; letter-spacing: 1px; font-weight: 600; font-family: cursive;">
                <span style="font-size: 24px; font-weight: 1000;">C</span>oding<span style="color:#C9A56E;"><span style="font-size: 24px;">A</span>lphas</span>
             </div>
        </a>
        
       

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-flex align-items-center " id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
               
                <li class="nav-item mt-1" style="font-size:13px;">
                    <a class="nav-link" href="#" id="running"></a>
                  </li>
                 <li class="nav-item mt-1 " style="font-size:13px;">
                   <a class="nav-link" href="#"> Draft in {{request.user.profile.first_name}} {{request.user.profile.last_name}}</a>
                 </li>
                
                
             
            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown ml-2" style="font-size:13px;">
                <a class="nav-link dropdown-toggle d-flex align-items-center text-dark" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                 <img src="/media/{{request.user.profile.avatar}}" style="width:30px; height:30px;" class="mr-1 rounded-circle">{{request.user}}
                </a>
                <div class="dropdown-menu dropdown-menu-right border-0 shadow-sm" style="font-size: 13px; width:240px; " aria-labelledby="navbarDropdown">
                  <a class="dropdown-item pt-2 pb-2" href="/profile/{{request.user}}/"><i class="fa fa-user fa2"></i> Profile</a>
                  <a class="dropdown-item pt-2 pb-2" href="/profile/{{request.user}}/?method=Articles"><i class="fa fa-rss" style="color: #C9A56E;"></i> Stories</a>
                  <a class="dropdown-item pt-2 pb-2" href="/profile/{{request.user}}/?method=Stats"><i class="fa fa-bar-chart" style="color: #C9A56E;"></i> Stats</a>
                  <a class="dropdown-item pt-2 pb-2" href="/profile/{{request.user}}/?method=Bookmarks"><i class="fa fa-bookmark-o" style="color: #C9A56E;"></i> Bookmarks</a>
                  <a class="dropdown-item pt-2 pb-2" href="/profile/{{request.user}}/?method=Notifications"><i class="fa fa-bell fa2" ></i> Notifications</a>
                  <a class="dropdown-item pt-2 pb-2" href="/settings/"><i class="fa fa-cog" style="color: #C9A56E;"></i> Settings and Privacy</a>
              
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item d-flex justify-content-center" href="/logout/" style="color: #C9A56E;">Logout</a>
                </div>
              </li>
            {% else %}

            <li class="nav-item mt-1 d-flex justify-content-start ml-3 " style="font-size:12px;">
                <a class="nav-link btn btn-sm rounded-0" href="/signin/" style="color:#C9A56E">Sign In</a>
            </li>
            
            {% endif %}
            

        </ul>
        </div>
        

     </div>
</div>
</nav>
<div class="section" >
    <form id="myform" method="POST" enctype="multipart/form-data" >
        {% csrf_token %}
        <div style="background: #C9A56E; min-height:300px; " class="pt-5" >
            <div class="d-flex justify-content-center mt-5" >
                        
                <div style="width:100%;  position: absolute; padding-top:auto; margin-left:auto;  margin-right:auto; color:#202C33; font-size: 100px; font-weight: 600; left:0; right:0; text-align: center; ">
                   <center>
                    <img src="{% static 'svg/upload.svg' %}" style="width:200px;  {% if edit %}
                    display:none;
                  {% endif %}" id="upload" alt="Cover Picture">
                   </center>

                 </div>
                 {{form.image|as_crispy_field}}
                 <input type="hidden" name="instance" value="{{id}}" id="hidden_instance">
            </div>
            <div id="preview" style="display: none;" class="">
                <div class="d-flex justify-content-end">
                    <a class="btn btn-sm" onclick="show()" style="width:50px;"><i class="fa fa-close "></i></a>
                </div>
                <div  class="d-flex justify-content-center">
                    <img id="blah" src="/media/{{link}}/" alt="your image" style="display: none;  width:100%;" >
                </div>
    
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="mt-5">
                        {{form.title|as_crispy_field}}
                    </div>
                </div>
                <div class="col-12">
                    <div class="d-flex justify-content-center">
                    {{form.content|as_crispy_field}}
                    {{form.media}}
                </div>
                </div>
            </div>
        </div>
        </form>
</div>

{% endblock %}



{% block script %}

<script>
    

  

    DecoupledEditor
            .create( document.querySelector( '#editor' ) ,{
                placeholder:"Write your story here. Add images or a video for visual impact.",
               
                ckfinder: {
                    uploadUrl: 'http://localhost:8000/blogs/upload/body/',
                   
                },
            })
            .then( editor => {
                const toolbarContainer = document.querySelector( '#toolbar-container' );

                toolbarContainer.appendChild( editor.ui.view.toolbar.element );
            } )
            .catch( error => {
                console.error( error );
            } );
        


   $(function(){
  $('#div_id_image').change(function(){
    document.getElementById("blah").style.display="block";
    document.getElementById("preview").style.display="block";
    if (this.files && this.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah')
                    .attr('src', e.target.result)
                    .css('width', '100%');
                    
            };

            reader.readAsDataURL(this.files[0]);
        }

        document.getElementById("div_id_image").style.display = 'none';
        document.getElementById("upload").style.display = 'none';
        
  });

});

function show(){
    document.getElementById("blah").style.display="none";
    document.getElementById("preview").style.display="none";
    document.getElementById("div_id_image").style.display = 'block';
        document.getElementById("upload").style.display = 'block';
}

function data_submit(){
document.getElementById('running').innerHTML = "Saving...";
var formdata = new FormData($('#myform')[0]);
formdata.append("value",document.getElementById('editor').innerHTML);
formdata.append("id",document.getElementById('hidden_instance').value);
formdata.append("method","create");
$.ajax({
            type:'POST',
            url: '/blogs/save/',
            data:formdata,
            processData: false,
    contentType: false,
            success:function(data){
                data = JSON.parse(data);
                if (data['status'] == 1){
                    document.getElementById('running').innerHTML = 'Saved';
                    $("#running").children().delay(5000).fadeOut(800); 
                    document.getElementById('hidden_instance').value = data['id'];
                    
                } 
                else{
                    document.getElementById('running').innerHTML = 'Start Writing';
                    $("#running").children().delay(5000).fadeOut(800);
                }

                
                
            },
            error: function(data){
                console.log("error");
                console.log(data);
            }
        });

    }
    setInterval(function() {
      data_submit();
    }, 10000);
    $(document).bind('keydown', function(e) {
  if(e.ctrlKey && (e.which == 83)) {
    e.preventDefault();
    data_submit();
    return false;
  }
});
</script>

{% endblock %}